<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Neev Technologies
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Neevtech
 *
 * @category   Neev
 * @package    Neev_AmazonPaymentIndia
 * @copyright  Copyright (c) 2014 (http://www.neevtech.com)
 * @author     Milind Desai / Neev Technologies
 */
?>
<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->helper('checkout')->__('Back') ?></a></p>
        <button type="button" class="button" onclick="checkout.saveShippingMethod()"><span><span><?php echo $this->helper('checkout')->__('Continue') ?></span></span></button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->helper('checkout')->__('Loading next step...') ?>" title="<?php echo $this->helper('checkout')->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->helper('checkout')->__('Loading next step...') ?>
        </span>
    </div>
</form>
