<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Neev Technologies
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Neevtech
 *
 * @category   Neev
 * @package    Neev_AmazonPaymentIndia
 * @copyright  Copyright (c) 2014 (http://www.neevtech.com)
 * @author     Milind Desai / Neev Technologies
 */
?>
<div class="checkoutbyamazon-badge">
    <img src="<?php echo $this->getAmazonBadgeUrl(); ?>" alt="<?php echo $this->__('Checkout by Amazon'); ?>" title="<?php echo $this->__('Checkout by Amazon'); ?>" />
</div>