<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Neevtech
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from neev  
 *
 * @category   Neev
 * @package    Neev_AmazonPaymentIndia
 * @copyright  Copyright (c) 2011 - 2014 neev   (http://www.neevtech.com)
 * @author     Milind Desai / Neevtech
 */
?>
<div id="cbaxmlButton-i1RGdr46u4-1417167499">
<img src="https://paywithamazon-sandbox.amazon.in/gp/cba/button?cartOwnerId=A111O19OHHZ2JW&size=medium&color=tan&background=white"/><br></div>
    <script>
    RenderCBAButtonById = function(ordervalue, buttonid) {
    var standard1 = new CBA.Widgets.StandardCheckoutWidget({
    merchantId: "A111O19OHHZ2JW",
    orderInput: {
    format: "XML",
    value: ordervalue}
    }).render(buttonid);
    }
    </script>
    <script language="javascript" type="text/javascript">
    RenderCBAButtonById("<?php echo $this->createOrderInputValue(); ?>", "cbaxmlButton-i1RGdr46u4-1417167499");
</script>
