<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Neev Technologies
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Neevtech
 *
 * @category   Neev
 * @package    Neev_AmazonPaymentIndia
 * @copyright  Copyright (c) 2014 (http://www.neevtech.com)
 * @author     Milind Desai / Neev Technologies
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head"><?php echo Mage::helper('amazonpaymentindia')->__('Debug data') ?></h3></td>
            <td class="form-buttons"><button style="" onclick="setLocation('<?php echo $this->getUrl('amazonpaymentindia/adminhtml_debug/download'); ?>')" class="scalable" type="button"><span>Download as file</span></button></td>
        </tr>
    </tbody></table>
</div>
<div>
    <?php echo $this->getChildHtml('debug_info'); ?>
</div>
