<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Neevtech
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from neev  
 *
 * @category   neev
 * @package    neev_AmazonPaymentIndia
 * @copyright  Copyright (c) 2011 - 2014 neev   (http://www.neevtech.com)
 * @author     Milind Desai / Neevtech
 */
?>
<script type="text/javascript">//<![CDATA[
    document.observe('dom:loaded', function() {
        if ($('creative-system-config')) {
            $('creative-system-config').setStyle({
                display: 'block', backgroundImage: 'url(<?php echo $this->getSkinUrl('neev/images/amazon-payment-india-header-logo.png'); ?>)',
                backgroundPosition: '0 50%', backgroundRepeat: 'no-repeat', height: '27px', margin: '0', padding: '0',
                textIndent: '-9999px', cursor: 'auto'
            });
        }
        var menuItems = $$('#nav li.level0 > a > span');
        if (menuItems.length) {
            menuItems.each(function(item) {
                if (item.innerHTML == 'neev') {
                    item.setStyle({
                        display: 'block', backgroundImage: 'url(<?php echo $this->getSkinUrl('neev/images/amazon-payment-india-header-logo-white.png'); ?>)', overflow: 'hidden',
                        width: '100px', backgroundRepeat: 'no-repeat', backgroundPosition: 'center center', textIndent: '-9999px'
                    });
                }
            });
        }
    });
//]]></script>
