<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Neev Technologies
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Neevtech
 *
 * @category   Neev
 * @package    Neev_AmazonPaymentIndia
 * @copyright  Copyright (c) 2014 (http://www.neevtech.com)
 * @author     Milind Desai / Neev Technologies
 */
?>
<button type="submit" title="<?php echo $this->helper('checkout')->__('Place Order') ?>" class="button btn-checkout" onclick="checkout.saveOrder();"><span><span><?php echo $this->helper('checkout')->__('Place Order') ?></span></span></button>
