<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Neev Technologies
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Neevtech
 *
 * @category   Neev
 * @package    Neev_AmazonPaymentIndia
 * @copyright  Copyright (c) 2014 (http://www.neevtech.com)
 * @author     Milind Desai / Neev Technologies
 */
?>
<?php echo $this->__($this->getMethod()->getTitle()); ?><br />
<?php if ($this->getInfo()->getLastTransId()): ?>
    <?php echo $this->__('Amazon Payments ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) ?><br/>
<?php else: ?>
    <?php echo $this->__('Payment has not been processed yet') ?><br/>
<?php endif; ?>
